### PR TITLE
Added sendJSON method

### PR DESCRIPTION
**Pull request by bl4ckm0r3**
I have found myself writing a lot of JSON.stringify, so i made an utility method that will do it for you!

### CODE REVIEW

**Review by lukeed — COMMENTED** [review]
Hey, cool! 😃 Not sure why I didn't think to include this, I do it all the time too.

I'll make the changes, but how do you feel about calling it `json` instead of `sendJSON`?

**Comment by bl4ckm0r3** [comment]
No worries, that's the beauty of opensource!
Tbh i think JSON is kind of all caps (acronym).
I did a sendJson first but then changed for standard.
I think sendjson doesn't read as well as sendJSON or sendJson.
What do you think?
I am open to suggestions :)

**Comment by bl4ckm0r3** [comment]
I have just realised you meant just `json` instead of `sendJSON`.
I think clarity is better and `sendJSON` describes better what is going on.
But it's your library :)

**Comment by lukeed** [comment]
No problem 😆 I'm leaning towards `json()` because of bytes (lol) and it looks more like the Express response helper (`res.json({...})`), and people may be used to that.

Lemme ask around real quick for opinions and I'll get back shortly~

**Comment by SinisterBlade** [comment]
FWIW, I think just `json()` is clear enough. (And it looks prettier too! 😊)

**Comment by lukeed** [comment]
Me too 😄 That was also the consensus I got today when I asked others. 🙌

**Comment by lukeed** [comment]
Thank you @bl4ckm0r3~! 🎉

**Comment by bl4ckm0r3** [comment]
thank you @lukeed very nice library!
ps i have slept on it...like `json` better :D

**Comment by lukeed** [comment]
Haha, great!!

**Pull request merged**
